export const SET_FORECAST = 'SET_FORECAST';
export const SET_CURRENT_SEARCH = 'SET_CURRENT_SEARCH';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_FORECAST_LOAD_ERROR = 'SET_FORECAST_LOAD_ERROR';